/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Cat cat = new Cat();
//        Cat cat = new Cat();
//        Dog dog = new Dog();

        System.out.println(cat.saveCatInformation());
    }
}

interface Animal {
    public String animalCry();
}


// Interfaces can be one way of forcing other classes to implement a particular method
// Animal -> animalCry() implements interface
// Cat -> animalCry "meow"
// Dog -> animalCry "bark"
// Bird -> animalCry "crow"


// Animal animalCry() extends class
// Cat -> animalCry()
// Dog ->